apiVersion: redhatcop.redhat.io/v1alpha1
kind: GCPAuthEngineRole
metadata:
  labels:
    app.kubernetes.io/name: gcpauthenginerole
    app.kubernetes.io/instance: gcpauthenginerole-sample
    app.kubernetes.io/part-of: vault-config-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vault-config-operator
  name: gcpauthenginerole-sample
spec:
  authentication:
    path: vault-admin
    role: vault-admin
    serviceAccount:
      name: vault
  connection:
    address: 'https://vault.example.com'
  path: gcp
  name: "gcp-iam-role"
  type: "iam"
  boundServiceAccounts: {}
  boundProjects: {}
  addGroupAliases: false
  tokenTTL: ""
  tokenMaxTTL: ""
  tokenPolicies: []
  policies: []
  tokenBoundCIDRs: []
  tokenExplicitMaxTTL: ""
  tokenNoDefaultPolicy: false
  tokenNumUses: 0
  tokenPeriod: 0
  tokenType: ""
  maxJWTExp: ""
  allowGCEInference: false
  boundZones: []
  boundRegions: []
  boundInstanceGroups: []
  boundLabels: []

